import PolicyContact from '../components/common/PolicyContact'
import PolicyPageLayout from '../components/common/PolicyPageLayout'

const sections = [
  { title: 'Order Processing', content: <div><p>Orders are prepared after successful order acceptance and payment confirmation, subject to stock and serviceability. Processing may take longer during high demand, holidays, or events outside our reasonable control.</p><p className="mt-3 font-semibold text-brand-dark">TODO: Confirm the normal order-processing timeframe and order cut-off rules.</p></div> },
  { title: 'Shipping Coverage and Delivery Locations', content: <div><p>Delivery depends on the address and postal code being serviceable when the order is placed. We may be unable to accept or dispatch an order to an unsupported location.</p><p className="mt-3 font-semibold text-brand-dark">TODO: Confirm serviceable states, regions, postal codes, and any excluded locations.</p></div> },
  { title: 'Shipping Charges', content: <div><p>Shipping is charged once per order, regardless of the number of products or quantities in that order.</p><ul className="mt-3 list-disc space-y-1 pl-6"><li><strong>South India:</strong> ₹60 per order</li><li><strong>Rest of India:</strong> ₹90 per order</li></ul><p className="mt-3">South India currently includes Kerala, Tamil Nadu, Karnataka, Andhra Pradesh, Telangana, and Puducherry. The applicable shipping charge is calculated from the delivery State or Union Territory and displayed during checkout before payment.</p></div> },
  { title: 'Delivery Estimates', content: <div><p>Any delivery estimate shown at checkout or communicated after dispatch is an estimate, not a guarantee. Actual delivery may vary based on location, serviceability, carrier operations, and external conditions.</p><p className="mt-3 font-semibold text-brand-dark">TODO: Confirm normal estimated delivery timeframes.</p></div> },
  { title: 'Order Tracking', content: <p>Where tracking is available, details may be sent using the email address or phone number provided with the order. Tracking updates are supplied by the delivery provider and may not appear immediately after dispatch. Contact us with your order number if you need assistance.</p> },
  { title: 'Shipping Partners', content: <div><p>We may use suitable third-party logistics or delivery providers based on destination and service availability.</p><p className="mt-3 font-semibold text-brand-dark">TODO: Confirm the authorised courier or shipping partners, if they should be named publicly.</p></div> },
  { title: 'Delivery Delays', content: <p>Delays can result from carrier congestion, transport disruption, remote-area serviceability, address verification, public holidays, weather, natural events, government restrictions, or other circumstances beyond reasonable control. We will provide available assistance but cannot guarantee carrier timelines.</p> },
  { title: 'Incorrect or Incomplete Addresses', content: <p>You are responsible for providing a complete delivery address, correct postal code, and reachable phone number. Contact us immediately if a correction is needed. Changes may not be possible after processing or dispatch, and additional costs caused by incorrect details may be payable where permitted by law and disclosed to you.</p> },
  { title: 'Failed Delivery Attempts', content: <p>If nobody is available or the recipient cannot be contacted, the delivery provider may make another attempt, request collection, or return the parcel, depending on its process. Re-dispatch is not guaranteed and may involve an additional charge that will be communicated before it is incurred.</p> },
  { title: 'Damaged Packages', content: <p>If a parcel arrives leaking, open, crushed, or visibly tampered with, photograph the package and shipping label before opening where safe to do so. Do not consume an unsafe-looking product. Contact us promptly with your order number and evidence so we can investigate.</p> },
  { title: 'Lost Shipments', content: <p>If tracking is unavailable for an unusual period or a shipment appears lost, contact us. We will review the order and available carrier records and, if loss is confirmed, offer an appropriate replacement, refund, or other remedy subject to availability and applicable law.</p> },
  { title: 'Holidays, Weather, and Unforeseen Events', content: <p>Processing and delivery may be affected by public holidays, severe weather, natural disasters, strikes, transport interruptions, government action, emergencies, or other events outside reasonable control. Delivery will resume as soon as reasonably possible.</p> },
  { title: 'Contact Information', content: <PolicyContact subject="shipping, tracking, or delivery" /> },
]

export default function ShippingPolicyPage() {
  return <PolicyPageLayout title="Shipping Policy" sections={sections} />
}
